/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppThreatEventsRouteImport } from './routes/_app.threat-events'
import { Route as AppRiskSimulationRouteImport } from './routes/_app.risk-simulation'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppIntelligenceBriefRouteImport } from './routes/_app.intelligence-brief'
import { Route as AppAuditTrailRouteImport } from './routes/_app.audit-trail'
import { Route as AppAttackGraphRouteImport } from './routes/_app.attack-graph'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThreatEventsRoute = AppThreatEventsRouteImport.update({
  id: '/threat-events',
  path: '/threat-events',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskSimulationRoute = AppRiskSimulationRouteImport.update({
  id: '/risk-simulation',
  path: '/risk-simulation',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppIntelligenceBriefRoute = AppIntelligenceBriefRouteImport.update({
  id: '/intelligence-brief',
  path: '/intelligence-brief',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditTrailRoute = AppAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => AppRoute,
} as any)
const AppAttackGraphRoute = AppAttackGraphRouteImport.update({
  id: '/attack-graph',
  path: '/attack-graph',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack-graph': typeof AppAttackGraphRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/intelligence-brief': typeof AppIntelligenceBriefRoute
  '/overview': typeof AppOverviewRoute
  '/risk-simulation': typeof AppRiskSimulationRoute
  '/threat-events': typeof AppThreatEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack-graph': typeof AppAttackGraphRoute
  '/audit-trail': typeof AppAuditTrailRoute
  '/intelligence-brief': typeof AppIntelligenceBriefRoute
  '/overview': typeof AppOverviewRoute
  '/risk-simulation': typeof AppRiskSimulationRoute
  '/threat-events': typeof AppThreatEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/attack-graph': typeof AppAttackGraphRoute
  '/_app/audit-trail': typeof AppAuditTrailRoute
  '/_app/intelligence-brief': typeof AppIntelligenceBriefRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/risk-simulation': typeof AppRiskSimulationRoute
  '/_app/threat-events': typeof AppThreatEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attack-graph'
    | '/audit-trail'
    | '/intelligence-brief'
    | '/overview'
    | '/risk-simulation'
    | '/threat-events'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attack-graph'
    | '/audit-trail'
    | '/intelligence-brief'
    | '/overview'
    | '/risk-simulation'
    | '/threat-events'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/attack-graph'
    | '/_app/audit-trail'
    | '/_app/intelligence-brief'
    | '/_app/overview'
    | '/_app/risk-simulation'
    | '/_app/threat-events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/threat-events': {
      id: '/_app/threat-events'
      path: '/threat-events'
      fullPath: '/threat-events'
      preLoaderRoute: typeof AppThreatEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/risk-simulation': {
      id: '/_app/risk-simulation'
      path: '/risk-simulation'
      fullPath: '/risk-simulation'
      preLoaderRoute: typeof AppRiskSimulationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence-brief': {
      id: '/_app/intelligence-brief'
      path: '/intelligence-brief'
      fullPath: '/intelligence-brief'
      preLoaderRoute: typeof AppIntelligenceBriefRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit-trail': {
      id: '/_app/audit-trail'
      path: '/audit-trail'
      fullPath: '/audit-trail'
      preLoaderRoute: typeof AppAuditTrailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attack-graph': {
      id: '/_app/attack-graph'
      path: '/attack-graph'
      fullPath: '/attack-graph'
      preLoaderRoute: typeof AppAttackGraphRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAttackGraphRoute: typeof AppAttackGraphRoute
  AppAuditTrailRoute: typeof AppAuditTrailRoute
  AppIntelligenceBriefRoute: typeof AppIntelligenceBriefRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppRiskSimulationRoute: typeof AppRiskSimulationRoute
  AppThreatEventsRoute: typeof AppThreatEventsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAttackGraphRoute: AppAttackGraphRoute,
  AppAuditTrailRoute: AppAuditTrailRoute,
  AppIntelligenceBriefRoute: AppIntelligenceBriefRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppRiskSimulationRoute: AppRiskSimulationRoute,
  AppThreatEventsRoute: AppThreatEventsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
